package dev.fajar.starter.localization

import dev.fajar.starter.localization.resources.*
import org.jetbrains.compose.resources.StringResource

/** Explicit pairs keep runtime language changes portable across Android, iOS, desktop and Web. */
enum class AppString(val english: StringResource, val indonesian: StringResource) {
    Files(Res.string.files_en, Res.string.files_id),
    Upload(Res.string.upload_en, Res.string.upload_id),
    Download(Res.string.download_en, Res.string.download_id),
    UploadSample(Res.string.upload_sample_en, Res.string.upload_sample_id),
    DownloadSample(Res.string.download_sample_en, Res.string.download_sample_id),
    EmptyTransfers(Res.string.empty_transfers_en, Res.string.empty_transfers_id),
    TransferPreparing(Res.string.transfer_preparing_en, Res.string.transfer_preparing_id),
    TransferQueued(Res.string.transfer_queued_en, Res.string.transfer_queued_id),
    TransferRunning(Res.string.transfer_running_en, Res.string.transfer_running_id),
    TransferPaused(Res.string.transfer_paused_en, Res.string.transfer_paused_id),
    TransferFailed(Res.string.transfer_failed_en, Res.string.transfer_failed_id),
    TransferCompleted(Res.string.transfer_completed_en, Res.string.transfer_completed_id),
    Pause(Res.string.pause_en, Res.string.pause_id),
    Resume(Res.string.resume_en, Res.string.resume_id),
    Remove(Res.string.remove_en, Res.string.remove_id),
    Cancel(Res.string.cancel_en, Res.string.cancel_id),
    ErrorCancelled(Res.string.error_cancelled_en, Res.string.error_cancelled_id),
    SignInWithProvider(Res.string.sign_in_with_provider_en, Res.string.sign_in_with_provider_id),
    AppLocked(Res.string.app_locked_en, Res.string.app_locked_id),
    AppLockedDescription(
        Res.string.app_locked_description_en,
        Res.string.app_locked_description_id,
    ),
    UnlockApp(Res.string.unlock_app_en, Res.string.unlock_app_id),
    UseAccountSignIn(Res.string.use_account_sign_in_en, Res.string.use_account_sign_in_id),
    AppLock(Res.string.app_lock_en, Res.string.app_lock_id),
    AppLockDescription(Res.string.app_lock_description_en, Res.string.app_lock_description_id),
    EnableAppLock(Res.string.enable_app_lock_en, Res.string.enable_app_lock_id),
    DisableAppLock(Res.string.disable_app_lock_en, Res.string.disable_app_lock_id),
    DeviceAuthenticationFailed(
        Res.string.device_authentication_failed_en,
        Res.string.device_authentication_failed_id,
    ),
    DeviceAuthenticationUnavailable(
        Res.string.device_authentication_unavailable_en,
        Res.string.device_authentication_unavailable_id,
    ),
    SignIn(Res.string.sign_in_en, Res.string.sign_in_id),
    SignInDescription(Res.string.sign_in_description_en, Res.string.sign_in_description_id),
    Email(Res.string.email_en, Res.string.email_id),
    Password(Res.string.password_en, Res.string.password_id),
    PasswordPlaceholder(Res.string.password_placeholder_en, Res.string.password_placeholder_id),
    ShowPassword(Res.string.show_password_en, Res.string.show_password_id),
    HidePassword(Res.string.hide_password_en, Res.string.hide_password_id),
    Demo(Res.string.demo_en, Res.string.demo_id),
    DemoDescription(Res.string.demo_description_en, Res.string.demo_description_id),
    UseDemo(Res.string.use_demo_en, Res.string.use_demo_id),
    Loading(Res.string.loading_en, Res.string.loading_id),
    Overview(Res.string.overview_en, Res.string.overview_id),
    Activity(Res.string.activity_en, Res.string.activity_id),
    Account(Res.string.account_en, Res.string.account_id),
    ProfileDescription(Res.string.profile_description_en, Res.string.profile_description_id),
    DemoAccount(Res.string.demo_account_en, Res.string.demo_account_id),
    Workspace(Res.string.workspace_en, Res.string.workspace_id),
    PersonalWorkspace(Res.string.personal_workspace_en, Res.string.personal_workspace_id),
    Notifications(Res.string.notifications_en, Res.string.notifications_id),
    SignOut(Res.string.sign_out_en, Res.string.sign_out_id),
    RecentChanges(Res.string.recent_changes_en, Res.string.recent_changes_id),
    SampleData(Res.string.sample_data_en, Res.string.sample_data_id),
    SyncPending(Res.string.sync_pending_en, Res.string.sync_pending_id),
    LoadMore(Res.string.load_more_en, Res.string.load_more_id),
    RetryLoading(Res.string.retry_loading_en, Res.string.retry_loading_id),
    Refresh(Res.string.refresh_en, Res.string.refresh_id),
    WorkspaceSummary(Res.string.workspace_summary_en, Res.string.workspace_summary_id),
    Welcome(Res.string.welcome_en, Res.string.welcome_id),
    Projects(Res.string.projects_en, Res.string.projects_id),
    Active(Res.string.active_en, Res.string.active_id),
    Members(Res.string.members_en, Res.string.members_id),
    RecentActivity(Res.string.recent_activity_en, Res.string.recent_activity_id),
    ViewActivity(Res.string.view_activity_en, Res.string.view_activity_id),
    SaveActivity(Res.string.save_activity_en, Res.string.save_activity_id),
    UnsaveActivity(Res.string.unsave_activity_en, Res.string.unsave_activity_id),
    Skip(Res.string.skip_en, Res.string.skip_id),
    Back(Res.string.back_en, Res.string.back_id),
    StepOf(Res.string.step_of_en, Res.string.step_of_id),
    GetStarted(Res.string.get_started_en, Res.string.get_started_id),
    Continue(Res.string.continue_en, Res.string.continue_id),
    OnboardingWorkspace(Res.string.onboarding_workspace_en, Res.string.onboarding_workspace_id),
    OnboardingWorkspaceDescription(
        Res.string.onboarding_workspace_description_en,
        Res.string.onboarding_workspace_description_id,
    ),
    OnboardingActivity(Res.string.onboarding_activity_en, Res.string.onboarding_activity_id),
    OnboardingActivityDescription(
        Res.string.onboarding_activity_description_en,
        Res.string.onboarding_activity_description_id,
    ),
    OnboardingReady(Res.string.onboarding_ready_en, Res.string.onboarding_ready_id),
    OnboardingReadyDescription(
        Res.string.onboarding_ready_description_en,
        Res.string.onboarding_ready_description_id,
    ),
    AllowNotifications(Res.string.allow_notifications_en, Res.string.allow_notifications_id),
    TestNotification(Res.string.test_notification_en, Res.string.test_notification_id),
    CopyToken(Res.string.copy_token_en, Res.string.copy_token_id),
    ClearInbox(Res.string.clear_inbox_en, Res.string.clear_inbox_id),
    Retry(Res.string.retry_en, Res.string.retry_id),
    EmptyInbox(Res.string.empty_inbox_en, Res.string.empty_inbox_id),
    Unread(Res.string.unread_en, Res.string.unread_id),
    Open(Res.string.open_en, Res.string.open_id),
    TokenCopied(Res.string.token_copied_en, Res.string.token_copied_id),
    NotificationsEnabled(Res.string.notifications_enabled_en, Res.string.notifications_enabled_id),
    NotificationsBlocked(Res.string.notifications_blocked_en, Res.string.notifications_blocked_id),
    NotificationsUnavailable(
        Res.string.notifications_unavailable_en,
        Res.string.notifications_unavailable_id,
    ),
    NotificationSent(Res.string.notification_sent_en, Res.string.notification_sent_id),
    TryAgain(Res.string.try_again_en, Res.string.try_again_id),
    Settings(Res.string.settings_en, Res.string.settings_id),
    Language(Res.string.language_en, Res.string.language_id),
    LanguageDescription(Res.string.language_description_en, Res.string.language_description_id),
    SystemLanguage(Res.string.system_language_en, Res.string.system_language_id),
    English(Res.string.english_en, Res.string.english_id),
    Indonesian(Res.string.indonesian_en, Res.string.indonesian_id),
    UpdatedAt(Res.string.updated_at_en, Res.string.updated_at_id),
    FieldRequired(Res.string.field_required_en, Res.string.field_required_id),
    FieldInvalid(Res.string.field_invalid_en, Res.string.field_invalid_id),
    FieldExists(Res.string.field_exists_en, Res.string.field_exists_id),
    FieldRejected(Res.string.field_rejected_en, Res.string.field_rejected_id),
    ErrorValidation(Res.string.error_validation_en, Res.string.error_validation_id),
    ErrorUnauthorized(Res.string.error_unauthorized_en, Res.string.error_unauthorized_id),
    ErrorNetwork(Res.string.error_network_en, Res.string.error_network_id),
    ErrorTimeout(Res.string.error_timeout_en, Res.string.error_timeout_id),
    ErrorService(Res.string.error_service_en, Res.string.error_service_id),
    ErrorStorage(Res.string.error_storage_en, Res.string.error_storage_id),
    ErrorAccessDenied(Res.string.error_access_denied_en, Res.string.error_access_denied_id),
    AccountAccess(Res.string.account_access_en, Res.string.account_access_id),
    AccountRoles(Res.string.account_roles_en, Res.string.account_roles_id),
    PermissionSaveActivity(
        Res.string.permission_save_activity_en,
        Res.string.permission_save_activity_id,
    ),
    PermissionUploadFile(
        Res.string.permission_upload_file_en,
        Res.string.permission_upload_file_id,
    ),
    PermissionDownloadFile(
        Res.string.permission_download_file_en,
        Res.string.permission_download_file_id,
    ),
    RefreshAccess(Res.string.refresh_access_en, Res.string.refresh_access_id),
    MaintenanceTitle(Res.string.maintenance_title_en, Res.string.maintenance_title_id),
    MaintenanceDescription(
        Res.string.maintenance_description_en,
        Res.string.maintenance_description_id,
    ),
    UpdateRequiredTitle(Res.string.update_required_title_en, Res.string.update_required_title_id),
    UpdateRequiredDescription(
        Res.string.update_required_description_en,
        Res.string.update_required_description_id,
    ),
    UpdateRecommendedDescription(
        Res.string.update_recommended_description_en,
        Res.string.update_recommended_description_id,
    ),
    UpdateContactAdministrator(
        Res.string.update_contact_administrator_en,
        Res.string.update_contact_administrator_id,
    ),
    UpdateApp(Res.string.update_app_en, Res.string.update_app_id),
    Later(Res.string.later_en, Res.string.later_id),
    PolicyRefreshFailed(Res.string.policy_refresh_failed_en, Res.string.policy_refresh_failed_id),
    ErrorPermission(Res.string.error_permission_en, Res.string.error_permission_id),
    ErrorUnavailable(Res.string.error_unavailable_en, Res.string.error_unavailable_id),
    ErrorUnexpected(Res.string.error_unexpected_en, Res.string.error_unexpected_id),
}
